# -*- coding: utf-8 -*-
"""ZomatoCaseStudy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XzAgzSfAbxiGjpG9b3gfoIvG1llkgOFP
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

df=pd.read_csv('/content/drive/MyDrive/Zomato/zomato.csv',encoding='latin-1')

df.shape

df.head(4)

df.columns

df.info()

#cousins features have 9 null values
df.isna().sum()

df.describe()

#Finding the column with null values using list comprehension
[features for features in df.columns if df[features].isnull().sum()>0]

#analyzing the null values using heat map
#since the number of null values are 9 out of 9551 rows so its not visible clearly
sns.heatmap(df.isnull(),yticklabels=False)

df2=pd.read_excel('/content/drive/MyDrive/Zomato/Country-Code.xlsx')

df2.head(4)

df2.columns

df.columns

final_df=pd.merge(df,df2,on='Country Code',how='left')

final_df.head(2)

countries=final_df.Country.value_counts().index
countries

share=final_df.Country.value_counts().values
share

plt.title('Pie chart for Business Spread')
plt.pie(share[:3],labels=countries[:3],autopct='%1.2f%%')
plt.show()
#Zomato is mostly operating based out of india

final_df.columns

ratings=final_df.groupby(by=['Aggregate rating','Rating color','Rating text']).size().reset_index().rename(columns={0:'Rating count'})

ratings.head()

plt.figure(figsize=(12,10))
sns.barplot(x='Aggregate rating',y='Rating count',hue='Rating color',data=ratings,palette=['white','red','orange','yellow','green','green'])

"""## Observation : The count of people who give rating follows normal distribution with mean rating count **3.2**"""

#count plot
plt.title('Frequency of Rating color')
ax=sns.countplot(x='Rating color',data=ratings,hue='Rating color',palette=['blue','red','orange','yellow','green','green'],order=ratings['Rating color'].value_counts(ascending=False).index)
for label in ax.containers:
  ax.bar_label(label)
plt.show()

#find the companies that
ratings.head()

#find the countries name that gave zero rating
final_df[final_df['Aggregate rating']==0].groupby('Country').size().reset_index()

final_df.groupby(by=['Aggregate rating','Country']).size().reset_index().head(5)

"""### Observation: Maximum number of zero ratings were came from india"""

#findout which currency is used  by which country
final_df.columns

final_df.groupby(by=['Country','Currency']).size().reset_index()

#which countries do have online  delivery option
final_df.groupby(by=['Has Online delivery','Country']).size().reset_index()

"""**Few regions of india dont have online delivery option**"""

#method2
#which countries do have online  delivery option
final_df[final_df['Has Online delivery']=='Yes'].Country.value_counts()

"""**The online delivery option is availabe only in India and UAE**"""

final_df.columns

#Create a pie chart for cities distribution
City=final_df.City.value_counts().index
share=final_df.City.value_counts().values
plt.title('Pie chart for city share')
plt.pie(share[:5],labels=City[:5],autopct='%1.2f%%')
plt.show()

#find the top 10 Cuisines
cuisine_count=final_df["Cuisines"].value_counts().values
cuisine=final_df['Cuisines'].value_counts().index
cuisine

plt.title('Top 10 Cuisines')
plt.pie(cuisine_count[:10],labels=cuisine[:10],autopct='%1.2f%%')
plt.show()